### PR TITLE
Handle nil file when creating a new issue

### LINKED ISSUE #1326: Panic in v2.22.2 - nil pointer dereference regarding integer conversion overflow checks.
Running `gosec -exclude-generated ./...` on my codebase resulted in:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10315e4bc]

goroutine 1 [running]:
go/token.(*File).Name(...)
	go/token/position.go:114
github.com/securego/gosec/v2/analyzers.newIssue({0x1036d9daa, 0x4}, {0x14006967170, 0x2a}, 0x140047e6b40, 0x0, 0x2, 0x1)
	github.com/securego/gosec/v2/analyzers/util.go:70 +0x19c
github.com/securego/gosec/v2/analyzers.runConversionOverflow(0x14000e5d6c0)
	github.com/securego/gosec/v2/analyzers/conversion_overflow.go:84 +0x328
github.com/securego/gosec/v2.(*Analyzer).CheckAnalyzers(0x140004dc580, 0x14003211a00)
	github.com/securego/gosec/v2/analyzer.go:447 +0x3b0
github.com/securego/gosec/v2.(*Analyzer).Process(0x140004dc580, {0x0, 0x0, 0x0}, {0x140001e61e0, 0x1d, 0x3d?})
	github.com/securego/gosec/v2/analyzer.go:318 +0x374
main.main()
	github.com/securego/gosec/v2/cmd/gosec/main.go:477 +0xbdc
make: *** [gosec] Error 2
```

I will try to provide some example code to trigger this panic shortly.

Edit: seems to be related to using `./...`. Using `<path>/...`, e.g. `/path/to/module/...` does not panic.

### PR DESCRIPTION
**Pull request by ccojocar**
This can occur when there is a compilation issue into the code.

fixes #1326

### CODE REVIEW

File: analyzers/util.go [hunk 1]
```diff
@@ -62,6 +62,9 @@ func newIssue(analyzerID string, desc string, fileSet *token.FileSet,
 	pos token.Pos, severity, confidence issue.Score,
 ) *issue.Issue {
 	file := fileSet.File(pos)
+	if file == nil {
+		return &issue.Issue{}
+	}
```
Comment (ccoVeille) [inline analyzers/util.go:67]: 🎨 A comment would be appreciated, because it doesn't sound logic to have this.

It does when reading issue, but once merged it won't I think

Comment (ccojocar) [reply analyzers/util.go:68]: Done, thanks
