### PR TITLE
Go modules support for 1.12

### LINKED ISSUE #234: Go Modules support
### Summary 

Now that Go 1.11 is released with module support, more Go code throughout the ecosystem will be written as modules. Currently, gosec is unable to analyze code in modules. It would be great to update it to do so.

If this is something the gosec project is interested in, we (my company) are very interested in contributing a patch.

### Steps to reproduce the behavior

Here's an example. (For a real-world sample module, I followed along with https://dave.cheney.net/2018/07/14/taking-go-modules-for-a-spin on @davecheney's httpstat package, and pushed the changes to https://github.com/kr/httpstat/tree/mod.)

You can check out this module outside your `GOPATH` directory:

```
$ pwd
/Users/kr/demo
$ echo $GOPATH
/Users/kr/lib/go
$ git clone -b mod https://github.com/kr/httpstat.git
$ cd httpstat
$ go test
PASS
ok  	github.com/davecheney/httpstat	0.013s
```

But gosec isn't happy:

```
$ gosec *.go
[gosec] 2018/08/28 16:34:08 including rules: default
[gosec] 2018/08/28 16:34:08 excluding rules: default
2018/08/28 16:34:08 main.go is not within the $GOPATH and cannot be processed
```

### gosec version

`7fd94463edcbf12df2b5579682c003c3bffd6749`

### Go version (output of 'go version')

```
go version go1.11 darwin/amd64
```

### Operating system / Environment

```
$ go env GOOS GOARCH
darwin
amd64
```

### Expected behavior

Gosec analyzes the code and reports possible errors, as usual.

### Actual behavior

Error message.

### PR DESCRIPTION
**Pull request by azihsoyn**
This PR adds support for running this tool against Go modules.

Closes #234

### CODE REVIEW

**Comment by azihsoyn** [comment]
I'll fix CI using build tag for old version compatibility.

Thanks.

File: analyzer_test.go [hunk 1]
```diff
@@ -27,16 +25,17 @@ var _ = Describe("Analyzer", func() {
...
-			analyzer.LoadRules(rules.Generate().Builders())
-			dir, err := ioutil.TempDir("", "empty")
-			defer os.RemoveAll(dir)
-			Expect(err).ShouldNot(HaveOccurred())
-			err = analyzer.Process(buildTags, dir)
-			Expect(err).Should(HaveOccurred())
-			Expect(err.Error()).Should(MatchRegexp("no buildable Go source files"))
-		})
+		/*
+			It("should return an error if the package contains no Go files", func() {
```
Comment (gcmurphy) [inline analyzer_test.go]: Instead of commenting out the test can you please change this to use Ginko's `Skip()` with a message like `"Temporarily disabled"` or something similar until we figure out if this test is relevant anymore?

We're less likely to forget the test existed that way.

File: analyzer_test.go [hunk 2]
```diff
@@ -66,33 +65,35 @@ var _ = Describe("Analyzer", func() {
...
-			pkg1.Build()
-			pkg2.Build()
-			err := analyzer.Process(buildTags, pkg1.Path, pkg2.Path)
-			Expect(err).ShouldNot(HaveOccurred())
-			_, metrics, _ := analyzer.Report()
-			Expect(metrics.NumFiles).To(Equal(2))
-		})
+		/*
+			It("should be able to analyze multiple Go packages", func() {
+				analyzer.LoadRules(rules.Generate().Builders())
```
Comment (gcmurphy) [inline analyzer_test.go]: Same comment here regarding `Skip()`

File: analyzer_test.go [hunk 3]
```diff
@@ -105,36 +106,38 @@ var _ = Describe("Analyzer", func() {
...
-			}
-			fileErr := golangErrors[keys[0]]
-			Expect(len(fileErr)).To(Equal(1))
-			Expect(fileErr[0].Line).To(Equal(4))
-			Expect(fileErr[0].Column).To(Equal(5))
-			Expect(fileErr[0].Err).Should(MatchRegexp(`expected declaration, found '}'`))
-		})
+		/*
+			It("should report for Golang errors and invalid files", func() {
+				analyzer.LoadRules(rules.Generate().Builders())
```
Comment (gcmurphy) [inline analyzer_test.go]: Again prefer `Skip()` over comment

**Comment by azihsoyn** [comment]
Hi, @gcmurphy! Thanks for the review!

I'll fix your pointed places ASAP😄

File: analyzer_test.go (hunk 1 above)
Comment (ccojocar) [reply analyzer_test.go]: I am wondering if we should not get some of these tests passing. Is this behaviour removed from modules?

File: analyzer_test.go (hunk 2 above)
Comment (ccojocar) [reply analyzer_test.go]: Shouldn't this test pass? In a Go module are most likely multiple packages.

File: analyzer_test.go (hunk 3 above)
Comment (ccojocar) [reply analyzer_test.go]: See my comment above in the analyser. I think we should be able to get the errors from Go module loader. 

https://godoc.org/golang.org/x/tools/go/packages#Package

See the error field.

File: analyzer.go [hunk 4]
```diff
@@ -102,84 +102,40 @@ func (gosec *Analyzer) LoadRules(ruleDefinitions map[string]RuleBuilder) {
...
-				if errSlice, ok := gosec.errors[filePath]; ok {
-					gosec.errors[filePath] = append(errSlice, *newErr)
-				} else {
-					errSlice = make([]Error, 0)
-					gosec.errors[filePath] = append(errSlice, *newErr)
-				}
-			}
-		}
-	}
 	sortErrors(gosec.errors) // sorts errors by line and column in the file
```
[the remark this answers is not in the document]
Comment (azihsoyn) [reply analyzer.go]: I fixed it. thx 😄

**Comment by azihsoyn** [comment]
Hi, @gcmurphy, @ccojocar!

I fixed for all test passes.

But packages library may not be supported for 1.10 or older.

Can I remove test config from .travis.yml ?

**Comment by ccojocar** [comment]
Thanks @azihsoyn! It looks great!

> Can I remove test config from .travis.yml ?

Yes, Let's remove the 1.9 and 1.10 from travis config. I think that we will bump the version to `2.0.0` on the next release to make it clear that is a breaking change.

**Comment by ccojocar** [comment]
@gcmurphy Please could you have a look over this PR? I'm waiting for your thumb up before merging it. Thanks

**Comment by azihsoyn** [comment]
Thanks for review and merging!
