### PR TITLE
Fix typo on accessing G111 config

### LINKED ISSUE #794: NewDirectoryTraversal reads wrong config
### Summary 
[`NewDirectoryTraversal` ](https://github.com/securego/gosec/blob/607d607b516bf301996678c68dc371a0dba9a938/rules/directory-traversal.go#L46)reads the config for "G101" (`NewHardcodedCredentials`) instead of its own "G111"

This is a simple typo, but should the rule identifiers maybe be defined centrally like this?:

```go
const (
	G101_HardcodedCredentials = "G101"
	G102_BindsToAllNetworkInterfaces = "G102"
	//...
)
```

### PR DESCRIPTION
**Pull request by robot-5**
Fixes #794

### CODE REVIEW

**Review by ccojocar — APPROVED** [review]

File: rules/directory-traversal.go [hunk 1]
```diff
@@ -43,7 +43,7 @@ func (r *traversal) matchCallExpr(assign *ast.CallExpr, ctx *gosec.Context) (*go
 // NewDirectoryTraversal attempts to find the use of http.Dir("/")
 func NewDirectoryTraversal(id string, conf gosec.Config) (gosec.Rule, []ast.Node) {
 	pattern := `http\.Dir\("\/"\)|http\.Dir\('\/'\)`
-	if val, ok := conf["G101"]; ok {
+	if val, ok := conf["G111"]; ok {
```
Comment (ccojocar) [inline rules/directory-traversal.go:46]: You can use the `id` instead of `G111` to avoid an issue like this.
