### PR TITLE
fix: G602 support for nested conditionals with bounds check

### LINKED ISSUE #1200: G602: False positives for slices with bounds check on a higher hierarchy
### Summary 
Noticed that we're receiving errors for the G602 (slices out of bounds) rules when we have proper bound checks 
### Steps to reproduce the behavior
Code sample (inspired by the current unit tests):
```go
package main

import "fmt"

func main() {
	s := make([]byte, 0)
	if len(s) > 0 {
		switch s[0] {
		case 0:
			fmt.Println("zero")
			return
		default:
			fmt.Println(s[0])
			return
		}
	}
}
```

```go
package main

import "fmt"

func main() {
	s := make([]byte, 0)
	if len(s) > 0 {
		switch s[0] {
		case 0:
			b := true
			if b == true {
				// Should work for many-levels of nesting when the condition is not on the target slice
				fmt.Println(s[0])
			}
			return
		default:
			fmt.Println(s[0])
			return
		}
	}
}
```

``` go
package main

import "fmt"

func main() {
	s := make([]byte, 0)
	if len(s) > 0 {
		if len(s) > 1 {
			fmt.Println(s[1])
		}
		fmt.Println(s[0])
	}
}
```
### gosec version
`v2.20.1-0.20240826145712-bcec04e78483`
### Go version (output of 'go version')
`go version go1.23.0 darwin/arm64`
### Operating system / Environment
Mac OS Sonoma 14.6.1 (M1/arm64)
### Expected behavior
I'd expect these samples to not return any errors
### Actual behavior
They all return errors since the bounds check does not look deeper into conditionals

### PR DESCRIPTION
**Pull request by xWiiLLz**
Trying to fix  #1200 with this PR.
Suggestions/comments more than welcome

### CODE REVIEW

File: analyzers/slice_bounds.go [hunk 1]
```diff
@@ -118,32 +118,41 @@ func runSliceBounds(pass *analysis.Pass) (interface{}, error) {
...
-								delete(issues, instr)
-							}
-						case *ssa.IndexAddr:
-							indexValue, err := extractIntValue(tinstr.Index.String())
-							if err != nil {
-								break
-							}
-							if isSliceIndexInsideBounds(0, value, indexValue) {
-								delete(issues, instr)
+			var processBlock func(block *ssa.BasicBlock)
```
Comment (ccojocar) [inline analyzers/slice_bounds.go:121]: nit: I would use the short variable declaration here.

File: analyzers/slice_bounds.go [hunk 2]
```diff
@@ -118,32 +118,41 @@ func runSliceBounds(pass *analysis.Pass) (interface{}, error) {
...
+									break
+								}
+								if isSliceIndexInsideBounds(0, value, indexValue) {
+									delete(issues, instr)
+								}
 							}
 						}
+					} else if nestedIfInstr, ok := instr.(*ssa.If); ok {
+						for _, nestedBlock := range nestedIfInstr.Block().Succs {
+							processBlock(nestedBlock)
```
Comment (ccojocar) [inline analyzers/slice_bounds.go:149]: I would keep track of the depth of the recursion, and stop after 10 calls to avoid stack overflows and infinite loops.

**Review by ccojocar — CHANGES_REQUESTED** [review]
Thanks for contributing this fix. I left a few comments, it would be great if you could address them. Thanks again!

File: analyzers/slice_bounds.go (hunk 1 above)
Comment (xWiiLLz) [reply analyzers/slice_bounds.go:121]: You mean `processBlock := func(...)`? That's what I tried doing at first but the compiler yells since we're calling it recursively; I assume it has to see the declaration in its scope to use it.

File: analyzers/slice_bounds.go (hunk 2 above)
Comment (xWiiLLz) [reply analyzers/slice_bounds.go:149]: Sounds good, just noticed you had used that same pattern elsewhere (my bad). Will use `maxDepth` count instead of 10 as this is the pattern in use currently for `checkAllSlicesBounds` and `trackSliceBounds`

**Review by ccojocar — APPROVED** [review]
