### PR TITLE
G304: Issue when passing in perm or flag as variable to os.OpenFile()

### LINKED ISSUE #1318: G304: Issue when passing in perm or flag as variable to os.OpenFile()
For some reason gosec is happy with this code:
```
package main

import (
	"os"
	"path/filepath"
)

func open(fn string) {
	fh, err := os.OpenFile(filepath.Clean(fn), os.O_RDONLY, 0o600)
	if err != nil {
		panic(err)
	}
	defer fh.Close()
}

func main() {
	fn := "filename"
	open(fn)
}
```

while if it is changed to this I get a G304 error:
```
package main

import (
	"os"
	"path/filepath"
)

func open(fn string, perm os.FileMode) {
	fh, err := os.OpenFile(filepath.Clean(fn), os.O_RDONLY, perm)
	if err != nil {
		panic(err)
	}
	defer fh.Close()
}

func main() {
	fn := "filename"
	open(fn, 0o600)
}
```

The error:
```
[.../main.go:9] - G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
    8: func open(fn string, perm os.FileMode) {
  > 9: 	fh, err := os.OpenFile(filepath.Clean(fn), os.O_RDONLY, perm)
    10: 	if err != nil {
```

There seems to be the same problem if passing in the flag:
```
package main

import (
	"os"
	"path/filepath"
)

func open(fn string, flag int) {
	fh, err := os.OpenFile(filepath.Clean(fn), flag, 0o600)
	if err != nil {
		panic(err)
	}
	defer fh.Close()
}

func main() {
	fn := "filename"
	open(fn, os.O_RDONLY)
}
```

```
[.../main.go:9] - G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
    8: func open(fn string, flag int) {
  > 9: 	fh, err := os.OpenFile(filepath.Clean(fn), flag, 0o600)
    10: 	if err != nil {
```

Some additional information:
```
$ go version
go version go1.24.1 darwin/arm64
```

Probably not very helpful -version output (updated via `go install github.com/securego/gosec/v2/cmd/gosec@latest` just before opening the ticket)
```
$ gosec -version
Version: dev
Git tag:
Build date:
```

### PR DESCRIPTION
**Pull request by eshentials**
What
-Limit G304 to analyze only the path argument (arg[0]) for file APIs (os.Open, os.OpenFile, os.ReadFile, ioutil.ReadFile, os.Create).
-Ignore flag/perm variables to avoid false positives when non-path args are variable.
-Track filepath.Clean to treat cleaned identifiers as safe.
-Recognize safe joins: filepath.Join(const|resolvedBase, Clean(var)|cleanedIdent).
-Record Join(...) assigned to an identifier and consider it safe if that identifier is later cleaned.
-Fix a nil-context panic in trackJoinAssignStmt.

Why
-Prior behavior flagged G304 when perm or flag were variables, even though only the first argument is the file path. This caused false positives like:
-os.OpenFile(filepath.Clean(fn), os.O_RDONLY, perm)
-os.OpenFile(filepath.Clean(fn), flag, 0o600)Also fixed a panic where a nil analysis context was used in a call-list check.

How
-In readfile.Match, inspect only node.Args[0] (path).
-Add trackFilepathClean and isFilepathClean to respect filepath.Clean.
-Add isSafeJoin for filepath.Join(base, Clean(...)) or Join(constBase, cleanedIdent).
-Record Join(...) assignments via trackJoinAssignStmt and allow if the identifier is cleaned later.

Pass non-nil context to ContainsPkgCallExpr in trackJoinAssignStmt.

TestsRan rules suite: 42 passed, 0 failed.

Repro’d prior panic and confirmed it’s fixed.

Verified the three user examples:
-Static perm: OK, no G304.
-Var perm: OK, no G304.
-Var flag: OK, no G304.
-Still flags unsafe filepath.Join with variable path when not cleaned.

Impact
-Reduces false positives on G304 without weakening detection of unsafe path construction.
-Increases stability by removing nil-context panic.

Tests:
-go test ./rules -v

CLI:
-go build -o ./bin/gosec ./cmd/gosec
-./bin/gosec -include=G304 -fmt text -quiet /path/to/your/code
-JSON: ./bin/gosec -include=G304 -fmt json /path/to/your/code | jq .

fixes #1318

### CODE REVIEW

**Comment by eshentials** [comment]
@ccojocar please review

**Comment by eshentials** [comment]
@ccojocar I have added them, please do check.

File: rules/readfile.go [hunk 1]
```diff
@@ -90,54 +94,177 @@ func (r *readfile) trackFilepathClean(n ast.Node) {
...
+// trackJoin records when a Join() call result is assigned to an identifier
+// example: fullPath := filepath.Join(baseDir, cleanPath)
+func (r *readfile) trackJoin(n ast.Node) {
+	// n is expected to be a *ast.CallExpr (Join(...)) but the assignment is a different node.
+	// We will look for an enclosing AssignStmt if provided (the caller passes n which is the call)
+	if joinCall, ok := n.(*ast.CallExpr); ok && len(joinCall.Args) > 0 {
+		// We don't have direct access to the enclosing assignment here (since Match receives call exprs),
+		// so the practical approach is: when Match sees a Join call used in an assignment, it should call this helper
+		// with the assignment node. For simplicity, we will expect the caller to pass an AssignStmt.
+		_ = joinCall // caller should call trackJoin on the AssignStmt (see Match where we call it)
```
Comment (ccojocar) [inline rules/readfile.go]: Why this empty variable assignment needed here? This doesn't perform any action.

**Comment by ccojocar** [comment]
It seems that there are some lint issues. Please could you fix them?

**Comment by eshentials** [comment]
On it, I shall get back to you asap.

**Comment by eshentials** [comment]
@ccojocar I applied the changes, please check now.
