### PR TITLE
Various improvements in the SQL rules

### LINKED ISSUE #264: SQL String concatenation issues are ignored when multiple strings are concatenated
### Summary 
If a SQL query string is a concatenation of multiple strings gosec does not complain.

### Steps to reproduce the behavior
Check the following code snippet with `gosec`:
```
package main

import "database/sql"

func main() {
	query("; DELETE * FROM TABLE;")
}

func query(param string) {
	clt, _ := sql.Open("postgres", "")

	clt.Query("SELECT * FROM table" + "WHERE" + param)
}
```

### gosec version
Commit 41809946d461bcf365ab440a5d79bfbd1ce2ebbf
### Go version (output of 'go version')
go version go1.11.2 linux/amd64
### Operating system / Environment
Linux
### Expected behavior
Gosec finds issue `G202: SQL string concatenation (Confidence: HIGH, Severity: MEDIUM)`
### Actual behavior
Gosec does not find an issue.

### PR DESCRIPTION
**Pull request by ccojocar**
- Improve the SQL concatenation and string formatting rules to be applied only in the database/sql context
- Make the heuristic case insensitive
- Handle multiple strings concatenation 

fixes #264 #369 #345

### CODE REVIEW

File: issue_test.go [hunk 1]
```diff
@@ -91,21 +91,23 @@ var _ = Describe("Issue", func() {
 		})
 
 		It("should provide accurate line and file information for multi-line statements", func() {
-			var target *ast.BinaryExpr
```
Comment (gcmurphy) [inline issue_test.go:94]: Think the goal of this test was to make sure line range was accurate for findings that span multiple lines like this:

```go
2: 
3: q := `SELECT * FROM table WHERE` +
4:    os.Args[1] +  `= ?`
5:
```
So would return a range `3-4` rather than just `3` for example. The test code you've replaced here doesn't really do that afaict.

Comment (ccojocar) [reply issue_test.go:94]: Thanks for catching this. I changed the test to generate a multi-line finding.

File: rules/sql.go [hunk 2]
```diff
@@ -212,8 +293,11 @@ func NewSQLStrFormat(id string, conf gosec.Config) (gosec.Rule, []ast.Node) {
 			},
 		},
 	}
-	rule.calls.AddAll("fmt", "Sprint", "Sprintf", "Sprintln", "Fprintf")
+	rule.AddAll("*database/sql.DB", "Query", "QueryContext", "QueryRow", "QueryRowContext")
+	rule.AddAll("*database/sql.Tx", "Query", "QueryContext", "QueryRow", "QueryRowContext")
+	rule.fmtCalls.AddAll("fmt", "Sprint", "Sprintf", "Sprintln", "Fprintf")
 	rule.noIssue.AddAll("os", "Stdout", "Stderr")
 	rule.noIssueQuoted.Add("github.com/lib/pq", "QuoteIdentifier")
```
Comment (lukasaron) [inline rules/sql.go:300]: Why is here PostgreSQL import? It should be DB independent, right?

Comment (ccojocar) [reply rules/sql.go:300]: This package seems to be used by quite some people. It was already in there. I don't want to remove it as part of this refactoring since it appears to be useful to remove some false positives.

Comment (lukasaron) [reply rules/sql.go:300]: Do you feel this approach is a good practice? IMHO when the PostgreSQL hide some false alarms doesn't mean that for instance MySQL users can benefit from this.

**Comment by ccojocar** [comment]
@gcmurphy I pushed the fixes. Do you mind having another look? Thanks
