### PR TITLE
Fix false negative for SQL injection when using DB.QueryRow.Scan()

### LINKED ISSUE #713: False negative for SQL injection when using DB.QueryRow.Scan()
### Summary 

If the call to Row.Scan() is in the same expression as DB.QueryRow() SQL injection vulnerability is not detected.

### Steps to reproduce the behavior

Works (G201 reported):
```
var name string
query := fmt.Sprintf(`
	SELECT
		name
	FROM
		users
	WHERE user_id = '%s' LIMIT 1`, "abcd")
row := db.QueryRow(query)
err := row.Scan(&name)
```

Does not work (nothing reported):
```
var name string
query := fmt.Sprintf(`
	SELECT
		name
	FROM
		users
	WHERE user_id = '%s' LIMIT 1`, "abcd")
err := db.QueryRow(query).Scan(&name)
```

### gosec version

v2.9.0

### Go version (output of 'go version')

go version go1.17.1 linux/amd64

### Operating system / Environment

Ubuntu 20.04 64-bit / golang:1.17 Docker image

### Expected behavior

G201 is detected

### Actual behavior

G201 is not detected

### PR DESCRIPTION
**Pull request by kaiili**
Problem
fixes #713

Details :
can be seen in #713.
G201 regexp only match callexpr once.
If there is a sqlquery like the following, there will be problems with matching.

func main() {
	var name string
	db, err := sql.Open("sqlite3", ":memory:")
	if err != nil {
		panic(err)
	}
	q := fmt.Sprintf("SELECT name FROM users where id = '%s'", os.Args[1])
	err = db.QueryRow(q).Scan(&name)
	if err != nil {
		panic(err)
	}
	defer db.Close()
}

Solution
Add an extra check befor checkQuery.

### CODE REVIEW

File: rules/sql.go [hunk 1]
```diff
@@ -261,6 +261,21 @@ func (s *sqlStrFormat) Match(n ast.Node, ctx *gosec.Context) (*gosec.Issue, erro
 	switch stmt := n.(type) {
 	case *ast.AssignStmt:
 		for _, expr := range stmt.Rhs {
+			// when expr is CallExpr and Call.Fun.X is CallExpr ,check Call.Fun.X
+			if Call, ok := expr.(*ast.CallExpr); ok {
```
Comment (ccojocar) [inline rules/sql.go:265]: please could you rename the `Call` to `call`, normally the local variables are not capitalised

File: rules/sql.go [hunk 2]
```diff
@@ -261,6 +261,21 @@ func (s *sqlStrFormat) Match(n ast.Node, ctx *gosec.Context) (*gosec.Issue, erro
...
+				Selector, ok := Call.Fun.(*ast.SelectorExpr)
```
Comment (ccojocar) [inline rules/sql.go:266]: `Selector` => rename to `selector`

File: testutils/source.go [hunk 3]
```diff
@@ -1189,6 +1189,75 @@ func main(){
 		panic(err)
 	}
 	defer rows.Close()
+<<<<<<< HEAD
```
Comment (ccojocar) [inline testutils/source.go:1192]: This is a left over from git rebase. Please could you remove it?

File: testutils/source.go [hunk 4]
```diff
@@ -1189,6 +1189,75 @@ func main(){
...
+	if err != nil {
+		panic(err)
+	}
+	q := fmt.Sprintf("SELECT name FROM users where id = '%s'", os.Args[1])
+	err = db.QueryRow(q).Scan(&name)
+	if err != nil {
+		panic(err)
+	}
+	defer db.Close()
+=======
```
Comment (ccojocar) [inline testutils/source.go:1259]: left over from git rebase

File: testutils/source.go [hunk 5]
```diff
@@ -1189,6 +1189,75 @@ func main(){
...
+>>>>>>> 58058af0c8275f11249a71f18fc548bbd7b97ccc
```
Comment (ccojocar) [inline testutils/source.go:1260]: The same this one is from git rebase.

File: rules/sql.go [hunk 6]
```diff
@@ -261,6 +261,21 @@ func (s *sqlStrFormat) Match(n ast.Node, ctx *gosec.Context) (*gosec.Issue, erro
 	switch stmt := n.(type) {
 	case *ast.AssignStmt:
 		for _, expr := range stmt.Rhs {
+			// when expr is CallExpr and Call.Fun.X is CallExpr ,check Call.Fun.X
```
Comment (ccojocar) [inline rules/sql.go:264]: Please remove this comment since this information can be read directly from the code

File: rules/sql.go [hunk 7]
```diff
@@ -261,6 +261,21 @@ func (s *sqlStrFormat) Match(n ast.Node, ctx *gosec.Context) (*gosec.Issue, erro
...
+			if Call, ok := expr.(*ast.CallExpr); ok {
+				Selector, ok := Call.Fun.(*ast.SelectorExpr)
+				if !ok {
+					continue
+				}
+				sqlQueryCall, ok := Selector.X.(*ast.CallExpr)
+				// checkQuery when success get sqlQuery CallExpr and Selector contains Callexpr
```
Comment (ccojocar) [inline rules/sql.go:271]: Please remove this comment, this info can be read directly from the code

**Review by ccojocar — CHANGES_REQUESTED** [review]
Thank for rebasing the pull request. I left a few review comments. It would be great if you could have a look at them. Please could you also check the tests, there is one test failing. Thanks again!
